version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5

volumes:
  mongo-data:
